// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Datas.datas;
using Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Options;

#nullable disable

namespace Datas
{
    public partial class CadastroContext : DbContext
    {
        private readonly ConnectionString connectionStringsConfig;
        public CadastroContext(IOptions<ConnectionString> ConnectionStringConfig)
        {
            connectionStringsConfig = ConnectionStringConfig.Value;
        }

        public CadastroContext(DbContextOptions<CadastroContext> options, IOptions<ConnectionString> connectionStringsCofingOptions)
            : base(options)
        {
            connectionStringsConfig = connectionStringsCofingOptions.Value;
        }

        public virtual DbSet<DadosCliente> DadosClientes { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Latin1_General_CI_AS");

            modelBuilder.Entity<DadosCliente>(entity =>
            {
                entity.HasKey(e => e.Codigo)
                    .HasName("PK__DadosCli__06370DAD86FD6BAA");

                entity.ToTable("DadosClientes");

                entity.Property(e => e.Nome)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.cpf)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.telefone)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
